version: '3.8'

networks:
  mynetwork:
    name: ${APP_NAME}-network

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}-nginx-container
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./api:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
    networks:
      - mynetwork
    links:
      - "php81-service:php-fpm"

  # php
  php81-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ${APP_NAME}-php81-container
    #user: "${USERID}:${GROUPID}"
    working_dir: /var/www/
    ports:
      - "9009:9000"
    volumes:
      - ./api:/var/www
      - ./docker/php/config/99-php.ini:/usr/local/etc/php/conf.d/99-php.ini
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/01-xdebug.ini
    networks:
      - mynetwork

  # mysql
  mysql8-service:
    image: mysql:8.0
    container_name: ${APP_NAME}-mysql8-container
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
    networks:
      - mynetwork

  mailcatcher:
    image: schickling/mailcatcher
    container_name: ${APP_NAME}-mailcatcher-container
    ports:
      - "1080:1080"
      - "1025:1025"